language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

branches:
  - master

before_script: 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then composer require --dev phpunit/phpunit ^4.8; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev phpunit/phpunit ^4.8; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev phpunit/phpunit ^5.7; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer require --dev phpunit/phpunit ^6.1; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require --dev phpunit/phpunit ^6.1; fi
